[general]
import = ["/home/pisce/.local/share/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11
normal      = { family = "MesloLGS Nerd Font", style  = "Regular" }
bold        = { family = "MesloLGS Nerd Font", style  = "Bold" }
italic      = { family = "MesloLGS Nerd Font", style  = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font", style  = "Bold Italic" }

[scrolling]
history = 0

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.9
padding = { x = 4, y = 3 }

